apiVersion: v1
kind: Service
metadata:
  labels:
    app: ankit-django
  name: ankit-django
  namespace: ankit
spec:
  type: NodePort
  ports:
  - name: "ankit-django"
    port: 5000
    targetPort: 8000
    nodePort: 30600
  selector:
    app: ankit-django